# Generated by Django 5.1.1 on 2024-11-06 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FCM_DJANGO_FCMDEVICE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SendNotificacionPush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('mensaje', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuarios', models.ManyToManyField(blank=True, related_name='notificaciones_push', to=settings.FCM_DJANGO_FCMDEVICE_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_notificacion', models.IntegerField(blank=True, choices=[(1, 'Cliene'), (2, 'Administrador')], null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.FCM_DJANGO_FCMDEVICE_MODEL)),
            ],
        ),
    ]
