# Generated by Django 5.1.1 on 2024-11-07 03:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
        migrations.swappable_dependency(settings.FCM_DJANGO_FCMDEVICE_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendnotificacionpush',
            name='usuarios',
            field=models.ManyToManyField(related_name='notificaciones_push', to=settings.FCM_DJANGO_FCMDEVICE_MODEL),
        ),
    ]
