# Generated by Django 5.1.1 on 2024-11-07 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_alter_sendnotificacionpush_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendnotificacionpush',
            name='notificacion_enviada',
            field=models.BooleanField(default=False),
        ),
    ]
