# Generated by Django 5.1.1 on 2024-11-02 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notificaciones', '0003_suscripcionnotificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcionnotificacion',
            name='modelo',
            field=models.ForeignKey(limit_choices_to={'app_label__in': ['actividades', 'actividades', 'clientes', 'clientes', 'clientes', 'componentes', 'galeria', 'main', 'main', 'streamblocks'], 'model__in': ['progreso', 'detalleprogreso', 'cliente', 'proyecto', 'userprofile', 'proyectocomponentes', 'comentario', 'sitio', 'mensaje', 'proyectocomponentes']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
