# Generated by Django 5.1.1 on 2024-11-07 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0003_sendnotificacionpush_notificacion_enviada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendnotificacionpush',
            name='notificacion_enviada',
        ),
    ]
