# Generated by Django 5.1.1 on 2024-11-02 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0004_alter_suscripcionnotificacion_modelo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suscripcionnotificacion',
            name='titulo',
        ),
    ]
