# Generated by Django 5.1.1 on 2024-11-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0004_remove_sendnotificacionpush_notificacion_enviada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarionotificacion',
            name='tipo_notificacion',
            field=models.IntegerField(blank=True, choices=[(1, 'Cliene'), (2, 'Administrador')], default=1, null=True),
        ),
    ]
