# Generated by Django 5.1.1 on 2024-11-12 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0005_alter_usuarionotificacion_tipo_notificacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioNotificacion',
        ),
    ]
