# Generated by Django 5.1.1 on 2024-11-02 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0005_remove_suscripcionnotificacion_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcionnotificacion',
            name='titulo',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
