# Generated by Django 5.1.1 on 2024-11-05 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notificaciones', '0006_suscripcionnotificacion_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcionnotificacion',
            name='mensaje',
            field=models.TextField(blank=True, help_text='Opcional - Se tiene un mensaje predefiniodo,             el mensaje ira despues al predefinido', null=True, verbose_name='Mensaje'),
        ),
        migrations.AlterField(
            model_name='suscripcionnotificacion',
            name='modelo',
            field=models.OneToOneField(limit_choices_to={'app_label__in': ['actividades', 'actividades', 'clientes', 'clientes', 'clientes', 'componentes', 'galeria', 'main', 'main', 'streamblocks'], 'model__in': ['progreso', 'detalleprogreso', 'cliente', 'proyecto', 'userprofile', 'proyectocomponentes', 'comentario', 'sitio', 'mensaje', 'proyectocomponentes']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='suscripcionnotificacion',
            name='titulo',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
