# Generated by Django 5.1.1 on 2024-10-11 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.FloatField()),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.actividad')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.grupoactividades')),
            ],
            options={
                'unique_together': {('actividad', 'grupo')},
            },
        ),
    ]
