# Generated by Django 5.1.1 on 2024-10-11 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_actividadgrupo'),
        ('main', '0007_remove_supervisor_name_supervisor_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.grupoactividades')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sitio')),
            ],
            options={
                'verbose_name': 'Proyecto con actividades',
                'verbose_name_plural': 'Proyectos con actividades',
            },
        ),
    ]
