# Generated by Django 5.1.1 on 2024-10-11 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0003_proyectoactividad'),
        ('main', '0007_remove_supervisor_name_supervisor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectoactividad',
            name='proyecto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.sitio'),
        ),
    ]
