# Generated by Django 5.1.1 on 2024-10-11 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0005_progreso_progresoactividad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProgresoActividad',
        ),
    ]
