# Generated by Django 5.1.1 on 2024-10-11 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0008_detalleprogreso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleprogreso',
            old_name='valor',
            new_name='porcentaje',
        ),
    ]
