# Generated by Django 5.1.1 on 2024-10-11 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0009_rename_valor_detalleprogreso_porcentaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleprogreso',
            name='mostrar',
            field=models.BooleanField(default=True),
        ),
    ]
