# Generated by Django 5.1.1 on 2024-10-11 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0010_detalleprogreso_mostrar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleprogreso',
            name='porcentaje',
            field=models.FloatField(default=0.0, verbose_name='Avance %'),
        ),
    ]
