# Generated by Django 5.1.1 on 2024-10-11 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0011_alter_detalleprogreso_porcentaje'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyectoactividad',
            options={'verbose_name': 'Proyecto con Actividades', 'verbose_name_plural': 'Proyectos con Actividades'},
        ),
        migrations.RenameField(
            model_name='actividadgrupo',
            old_name='numero',
            new_name='ponderación',
        ),
    ]
