# Generated by Django 5.1.1 on 2024-10-11 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0012_alter_proyectoactividad_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividadgrupo',
            old_name='ponderación',
            new_name='ponderacion',
        ),
    ]
