# Generated by Django 5.1.1 on 2024-10-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0013_rename_ponderación_actividadgrupo_ponderacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='progreso',
            name='activar',
            field=models.BooleanField(default=True),
        ),
    ]
