# Generated by Django 5.1.1 on 2024-10-12 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0014_progreso_activar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividadgrupo',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='actividadgrupo',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detalleprogreso',
            name='mostrar',
            field=models.BooleanField(default=True, verbose_name='Agregar'),
        ),
    ]
