# Generated by Django 5.1.1 on 2024-10-12 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0015_alter_actividadgrupo_options_actividadgrupo_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleprogreso',
            options={'ordering': ['actividad_grupo__order'], 'verbose_name': 'Detalle de Progreso', 'verbose_name_plural': 'Detalles de Progresos'},
        ),
    ]
