# Generated by Django 5.1.1 on 2024-10-12 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0016_alter_detalleprogreso_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='progreso',
            name='fecha_final',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progreso',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
