# Generated by Django 5.1.1 on 2024-10-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0017_progreso_fecha_final_progreso_fecha_inicio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleprogreso',
            options={'ordering': ['order'], 'verbose_name': 'Detalle de Progreso', 'verbose_name_plural': 'Detalles de Progresos'},
        ),
        migrations.AddField(
            model_name='detalleprogreso',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
