# Generated by Django 5.1.1 on 2024-10-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0019_proyectoactividad_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleprogreso',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización'),
        ),
    ]
