# Generated by Django 5.1.1 on 2024-10-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0021_alter_detalleprogreso_fecha_actualizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleprogreso',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización'),
        ),
    ]
