# Generated by Django 5.1.1 on 2024-10-28 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0022_alter_detalleprogreso_fecha_actualizacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleprogreso',
            old_name='fecha_actualizacion',
            new_name='fecha',
        ),
    ]
