# Generated by Django 5.1.1 on 2024-11-09 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0023_rename_fecha_actualizacion_detalleprogreso_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleprogreso',
            name='fecha',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Actualización'),
        ),
    ]
