# Generated by Django 5.1.1 on 2024-11-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0024_alter_detalleprogreso_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progreso',
            name='activar',
            field=models.BooleanField(default=True, verbose_name='Incluir'),
        ),
    ]
