# Generated by Django 5.1.1 on 2024-11-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0025_alter_progreso_activar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleprogreso',
            name='mostrar',
            field=models.BooleanField(default=True, verbose_name='Incluir'),
        ),
        migrations.AlterField(
            model_name='progreso',
            name='activar',
            field=models.BooleanField(default=True),
        ),
    ]
