# Generated by Django 5.1.1 on 2024-11-12 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0026_alter_detalleprogreso_mostrar_alter_progreso_activar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleprogreso',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_detalleprogresos', to=settings.AUTH_USER_MODEL),
        ),
    ]
