# docker-compose.yml
services:
  sup-db:
    image: postgres:15-alpine  
    container_name: postgres_db
    ports:
      - "5438:5432"
    env_file:
      - .env  
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - sup_network

  sup-redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6385:6379"
    networks:
      - sup_network

  sup-dj:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    command: ./entrypoint.sh
    volumes:
      - ./staticfiles:/app/staticfiles  
      - ./media:/app/media    
    ports:
      - "8006:8000"  
    env_file:
      - .env  
    depends_on:
      - sup-db
      - sup-redis
    networks:
      - sup_network

volumes:
  postgres_data:
  staticfiles:
  media:

networks:
  sup_network:
