# Generated by Django 5.1.1 on 2024-10-26 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageWithText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='folder/')),
                ('text', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Image with text',
                'verbose_name_plural': 'Images with text',
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Titulo')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Texto')),
                ('border', models.CharField(blank=True, choices=[('rojo', 'Rojo'), ('amarillo', 'Amarillo'), ('verde', 'Verde')], max_length=10, null=True, verbose_name='Color de borde')),
                ('user_show', models.BooleanField(default=True, verbose_name='Firma de Usuario')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
            },
        ),
    ]
