# Generated by Django 5.1.1 on 2024-10-27 16:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import streamfield.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('galeria', '0003_alter_icon_options_alter_icon_icon_alter_icon_name'),
        ('main', '0014_alter_sitio_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ImageWithText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='folder/')),
                ('text', models.TextField(blank=True, null=True)),
                ('border', models.CharField(blank=True, choices=[('rojo', 'Rojo'), ('amarillo', 'Amarillo'), ('verde', 'Verde'), ('gris', 'Gris'), ('azul', 'Azul')], max_length=10, null=True, verbose_name='Color de borde')),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Imagen con Texto',
            },
        ),
        migrations.CreateModel(
            name='OpenUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('text', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RadialProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Titulo')),
                ('progress', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje')),
                ('color', models.CharField(blank=True, choices=[('rojo', 'Rojo'), ('amarillo', 'Amarillo'), ('verde', 'Verde'), ('gris', 'Gris'), ('azul', 'Azul')], max_length=10, null=True, verbose_name='Color')),
            ],
        ),
        migrations.CreateModel(
            name='MessageWithIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=100, null=True)),
                ('color_icon', models.CharField(blank=True, choices=[('rojo', 'Rojo'), ('amarillo', 'Amarillo'), ('verde', 'Verde'), ('gris', 'Gris'), ('azul', 'Azul')], max_length=10, null=True, verbose_name='Color de Icono')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='galeria.icon')),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoComponentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', streamfield.fields.StreamField(blank=True, default=list, verbose_name='Componentes')),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_componentes', to='main.sitio')),
            ],
            options={
                'verbose_name': 'COMPONENTES',
                'verbose_name_plural': 'COMPONENTES',
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Titulo')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Texto')),
                ('border', models.CharField(blank=True, choices=[('rojo', 'Rojo'), ('amarillo', 'Amarillo'), ('verde', 'Verde'), ('gris', 'Gris'), ('azul', 'Azul')], max_length=10, null=True, verbose_name='Color de borde')),
                ('user_show', models.BooleanField(default=True, verbose_name='Firma de Usuario')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='texts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
            },
        ),
    ]
