# Generated by Django 5.1.1 on 2024-10-28 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamblocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='text',
            options={'verbose_name': 'Texto', 'verbose_name_plural': 'Textos'},
        ),
    ]
