# Generated by Django 5.1.1 on 2024-10-30 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamblocks', '0002_alter_text_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commments',
        ),
        migrations.AddField(
            model_name='openurl',
            name='text2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='openurl',
            name='text3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='openurl',
            name='url2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='openurl',
            name='url3',
            field=models.URLField(blank=True, null=True),
        ),
    ]
