# Generated by Django 5.1.1 on 2024-11-08 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamblocks', '0003_delete_commments_openurl_text2_openurl_text3_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagewithtext',
            options={'verbose_name': 'Imagen con Texto', 'verbose_name_plural': 'Imagenes con Texto'},
        ),
    ]
