# Generated by Django 5.1.1 on 2024-09-29 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0003_delete_avance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ASG', 'Asignado'), ('EJE', 'Ejecución'), ('TER', 'Terminado'), ('PTG', 'Postergado'), ('CAN', 'Cancelado')], default='EJE', max_length=3, verbose_name='Estado')),
                ('excavacion', models.DateField(blank=True, null=True, verbose_name='Exc.')),
                ('hormigonado', models.DateField(blank=True, null=True, verbose_name='Hor.')),
                ('montado', models.DateField(blank=True, null=True, verbose_name='Mon.')),
                ('empalmeE', models.DateField(blank=True, null=True, verbose_name='Ele.')),
                ('porcentaje', models.FloatField(default=0.0, verbose_name='Porcentaje')),
                ('fechaFin', models.DateField(blank=True, null=True, verbose_name='Fecha Fin')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('sitio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.sitio')),
            ],
            options={
                'verbose_name': 'Avance',
                'verbose_name_plural': 'Avance Proyectos',
            },
        ),
    ]
