# Generated by Django 5.1.1 on 2024-09-28 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contratista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Contratista')),
                ('cod', models.CharField(help_text='3 Caracteres', max_length=3, verbose_name='Codigo')),
            ],
        ),
        migrations.CreateModel(
            name='Sitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitio', models.CharField(max_length=10, null=True, verbose_name='Codigo Sitio')),
                ('entel_id', models.CharField(max_length=10)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('altura', models.IntegerField(blank=True, null=True, verbose_name='Altura')),
                ('lat', models.FloatField(blank=True, max_length=11, null=True, verbose_name='Latitud')),
                ('lon', models.FloatField(blank=True, max_length=11, null=True, verbose_name='Longitud')),
                ('ito', models.CharField(max_length=12, verbose_name='ITO')),
                ('contratista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.contratista')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='Avance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ASG', 'Asignado'), ('EJE', 'Ejecución'), ('TER', 'Terminado'), ('PTG', 'Postergado'), ('CAN', 'Cancelado')], default='EJE', max_length=10, verbose_name='Estado')),
                ('excavacion', models.DateField(blank=True, null=True, verbose_name='Exc.')),
                ('hormigonado', models.DateField(blank=True, null=True, verbose_name='Hor.')),
                ('montado', models.DateField(blank=True, null=True, verbose_name='Mon.')),
                ('empalmeE', models.DateField(blank=True, null=True, verbose_name='Ele.')),
                ('porcentaje', models.FloatField(default=0.0, verbose_name='Porcentaje')),
                ('fechaFin', models.DateField(blank=True, null=True, verbose_name='Fecha Fin')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('sitio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.sitio')),
            ],
            options={
                'verbose_name': 'Avance',
                'verbose_name_plural': 'Avance Proyectos',
            },
        ),
    ]
