# Generated by Django 5.1.1 on 2024-09-28 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Nombre')),
                ('cargo', models.CharField(choices=[('SUP', 'Supervisor'), ('PRE', 'Prevencionista')], max_length=3, verbose_name='Cargo')),
            ],
        ),
        migrations.RenameField(
            model_name='sitio',
            old_name='entel_id',
            new_name='cod_id',
        ),
        migrations.AlterField(
            model_name='avance',
            name='estado',
            field=models.CharField(choices=[('ASG', 'Asignado'), ('EJE', 'Ejecución'), ('TER', 'Terminado'), ('PTG', 'Postergado'), ('CAN', 'Cancelado')], default='EJE', max_length=3, verbose_name='Estado'),
        ),
    ]
