# Generated by Django 5.1.1 on 2024-09-29 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_avance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supervisor',
            options={'verbose_name': 'Supervisor', 'verbose_name_plural': 'Supervisores'},
        ),
        migrations.AlterField(
            model_name='sitio',
            name='cod_id',
            field=models.CharField(max_length=10, verbose_name='Codigo Cliente'),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='contratista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.contratista'),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='ito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.supervisor'),
        ),
        migrations.AlterField(
            model_name='sitio',
            name='lat',
            field=models.FloatField(default=1, max_length=11, verbose_name='Latitud'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sitio',
            name='lon',
            field=models.FloatField(default=1, max_length=11, verbose_name='Longitud'),
            preserve_default=False,
        ),
    ]
