# Generated by Django 5.1.1 on 2024-10-08 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_avance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avance',
            old_name='energia_def',
            new_name='ener_def',
        ),
        migrations.RenameField(
            model_name='avance',
            old_name='energia_prov',
            new_name='ener_prov',
        ),
    ]
