# Generated by Django 5.1.1 on 2024-10-13 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_supervisor_name_supervisor_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avance',
        ),
    ]
