# Generated by Django 5.1.1 on 2024-10-13 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_delete_avance'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitio',
            name='estado',
            field=models.CharField(blank=True, choices=[('ASG', 'Asignado'), ('EJE', 'Ejecución'), ('TER', 'Terminado'), ('PTG', 'Postergado'), ('CAN', 'Cancelado')], max_length=3, null=True, verbose_name='Estado'),
        ),
    ]
