# Generated by Django 5.1.1 on 2024-10-13 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('main', '0010_rename_supervisor_userprofile_alter_sitio_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitio',
            name='ito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.userprofile'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
