# Generated by Django 5.1.1 on 2024-10-13 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_userprofile_options'),
        ('main', '0011_alter_sitio_ito_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitio',
            name='ito',
            field=models.ForeignKey(blank=True, limit_choices_to={'cargo': 'SUP'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.userprofile'),
        ),
    ]
