# Generated by Django 5.1.1 on 2024-10-13 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_userprofile_proyectos_alter_cliente_cod'),
        ('main', '0012_alter_sitio_ito'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitio',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.proyecto'),
        ),
    ]
