# Generated by Django 5.1.1 on 2024-10-28 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_userprofile_cargo'),
        ('main', '0015_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(verbose_name='Comentario')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('activar', models.BooleanField(default=False)),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='main.sitio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='clientes.userprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
