# Generated by Django 5.1.1 on 2024-10-28 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_userprofile_cargo'),
        ('main', '0016_chat_delete_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='fecha_carga',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='mensaje',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='usuario',
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='main.chat')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='clientes.userprofile')),
            ],
        ),
    ]
