# Generated by Django 5.1.1 on 2024-10-28 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_chat_fecha_carga_remove_chat_mensaje_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='chat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='main.chat'),
        ),
    ]
