# Generated by Django 5.1.1 on 2024-10-28 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_mensaje_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='sitio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='main.sitio'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='main.chat'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='mensaje',
            field=models.CharField(max_length=500, verbose_name='Mensaje'),
        ),
    ]
