# Generated by Django 5.1.1 on 2024-10-28 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_chat_sitio_alter_mensaje_chat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='usuario',
        ),
    ]
