# Generated by Django 5.1.1 on 2024-10-28 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_userprofile_cargo'),
        ('main', '0020_remove_mensaje_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='clientes.userprofile'),
            preserve_default=False,
        ),
    ]
