# Generated by Django 5.1.1 on 2024-10-28 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_userprofile_cargo'),
        ('main', '0021_mensaje_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='main.chat'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='clientes.userprofile'),
        ),
    ]
