# Generated by Django 5.1.1 on 2024-10-30 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_userprofile_user'),
        ('main', '0024_alter_mensaje_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='chat',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='main.chat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='clientes.userprofile'),
            preserve_default=False,
        ),
    ]
