# Generated by Django 5.1.1 on 2024-10-30 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_mensaje_chat_alter_mensaje_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitio',
            name='cod_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Codigo Cliente'),
        ),
    ]
