# Generated by Django 5.1.1 on 2024-10-30 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_sitio_cod_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitio',
            name='contratista',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main.contratista'),
            preserve_default=False,
        ),
    ]
