# Generated by Django 5.1.1 on 2024-11-06 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_sitio_contratista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitio',
            name='contratista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.contratista'),
        ),
    ]
