# Generated by Django 5.1.1 on 2024-11-09 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_operador_alter_sitio_contratista_sitio_operador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitio',
            name='sitio',
            field=models.CharField(max_length=12, null=True, verbose_name='Codigo Sitio'),
        ),
    ]
