# Generated by Django 5.1.1 on 2024-11-12 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_sitio_contratista'),
        ('main', '0029_alter_sitio_sitio'),
    ]

    operations = [
    ]
