# Generated by Django 5.1.1 on 2024-10-26 22:21

import django.db.models.deletion
import streamfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0014_alter_sitio_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoComponentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', streamfield.fields.StreamField(blank=True, default=list, verbose_name='Componentes')),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sitio')),
            ],
        ),
    ]
