# Generated by Django 5.1.1 on 2024-10-13 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_userprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='proyectos',
            field=models.ManyToManyField(to='clientes.proyecto', verbose_name='Proyectos'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cod',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
