# Generated by Django 5.1.1 on 2024-10-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_userprofile_proyectos_alter_cliente_cod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cargo',
            field=models.CharField(choices=[('SUP', 'Supervisor'), ('PRE', 'Prevencionista'), ('ADM', 'Administrador'), ('CLI', 'Cliente'), ('SEG', 'Seguimiento'), ('CTT', 'Contratista')], max_length=3, verbose_name='Cargo'),
        ),
    ]
