# Generated by Django 5.1.1 on 2024-11-08 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_alter_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogoRedLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('logo', models.FileField(help_text='Formato PNG o SVG', upload_to='logos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'svg'])], verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Logo',
                'verbose_name_plural': 'Logos',
            },
        ),
    ]
