# Generated by Django 5.1.1 on 2024-11-08 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_logoredline'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='logo_mostrar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.logoredline'),
        ),
    ]
