# Generated by Django 5.1.1 on 2024-11-08 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_cliente_logo_mostrar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='clientes.cliente'),
        ),
    ]
