# Generated by Django 5.1.1 on 2024-11-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_userprofile_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tipo_notificacion',
            field=models.IntegerField(blank=True, choices=[(1, 'Cliente'), (2, 'Administrador')], default=1, null=True),
        ),
    ]
