# Generated by Django 5.1.1 on 2024-11-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_userprofile_tipo_notificacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuario'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tipo_notificacion',
            field=models.IntegerField(blank=True, choices=[(1, 'Cliente'), (2, 'Administrador'), (3, 'Equipo interno')], null=True),
        ),
    ]
