# Generated by Django 5.1.1 on 2024-10-21 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Utilice los controles de arrastrar y soltar para reordenar.', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Bloque de Contenido',
                'verbose_name_plural': 'Bloques de Contenido',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('orden', models.PositiveIntegerField(default=0)),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='ppp.bloque')),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_imagen', models.ImageField(upload_to='imagenes/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imgs', to='ppp.bloque')),
            ],
        ),
        migrations.AddField(
            model_name='bloque',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='ppp.proyecto'),
        ),
    ]
