# Generated by Django 5.1.1 on 2024-09-30 03:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0004_alter_supervisor_options_alter_sitio_cod_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_carga', models.DateField(default=django.utils.timezone.now)),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='main.sitio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_subidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes/')),
                ('descripcion', models.CharField(blank=True, max_length=52, null=True)),
                ('fecha_carga', models.DateField(default=django.utils.timezone.now)),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='main.sitio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_subidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imagenes',
            },
        ),
    ]
