# Generated by Django 5.1.1 on 2024-10-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='icon',
            options={'verbose_name': 'Icono', 'verbose_name_plural': 'Iconos'},
        ),
        migrations.AlterField(
            model_name='icon',
            name='icon',
            field=models.TextField(help_text='Codigo SVG https://icon-sets.iconify.design/', verbose_name='Icono'),
        ),
        migrations.AlterField(
            model_name='icon',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Nombre del Icono'),
        ),
    ]
