# Generated by Django 5.1.1 on 2024-11-11 19:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_alter_icon_options_alter_icon_icon_alter_icon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha_carga',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='fecha_carga',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
